DJANGO_SETTINGS_MODULE=atriaapp.heroku_settings python manage.py makemigrations
DJANGO_SETTINGS_MODULE=atriaapp.heroku_settings python manage.py migrate
DJANGO_SETTINGS_MODULE=atriaapp.heroku_settings python manage.py loaddata sample-data
