# Generated by Django 2.0.9 on 2019-01-10 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0003_auto_20181216_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtriaOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=40)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=8)),
            ],
        ),
    ]
