# Generated by Django 2.0.9 on 2019-01-27 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0005_auto_20190110_0142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atriaevent',
            old_name='program_zh',
            new_name='program_zh_hans',
        ),
        migrations.RenameField(
            model_name='atriaeventprogram',
            old_name='label_zh',
            new_name='label_zh_hans',
        ),
        migrations.RenameField(
            model_name='atriaorganization',
            old_name='org_name_zh',
            new_name='org_name_zh_hans',
        ),
    ]
