# Generated by Django 2.0.10 on 2019-02-10 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0006_auto_20190127_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtriaBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='AtriaEventAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_count', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True, max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='AtriaOrgAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField(max_length=4000)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True)),
                ('added_by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AtriaRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=8)),
                ('effective_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(max_length=20)),
                ('attendance_description', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='RelationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=20)),
                ('relation_description', models.CharField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name='atriaevent',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaOrganization'),
        ),
        migrations.AddField(
            model_name='atriaorganization',
            name='description',
            field=models.TextField(default='0', max_length=4000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atriaorganization',
            name='location',
            field=models.CharField(default='0', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atriarelationship',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaOrganization'),
        ),
        migrations.AddField(
            model_name='atriarelationship',
            name='relation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.RelationType', verbose_name='relationship'),
        ),
        migrations.AddField(
            model_name='atriarelationship',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atriaorgannouncement',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaOrganization'),
        ),
        migrations.AddField(
            model_name='atriaeventattendance',
            name='attendance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.EventAttendanceType'),
        ),
        migrations.AddField(
            model_name='atriaeventattendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaEvent'),
        ),
        migrations.AddField(
            model_name='atriaeventattendance',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='atriabookmark',
            name='bookmark_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.EventAttendanceType'),
        ),
        migrations.AddField(
            model_name='atriabookmark',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaEvent'),
        ),
        migrations.AddField(
            model_name='atriabookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
