# Generated by Django 2.0.10 on 2019-02-15 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0007_auto_20190210_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtriaCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(blank=True, max_length=40)),
                ('org_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaOrganization')),
                ('user_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='atriaevent',
            name='org',
        ),
        migrations.AddField(
            model_name='atriaevent',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaCalendar'),
        ),
    ]
