# Generated by Django 2.1.7 on 2019-04-04 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0004_auto_20190328_0248'),
        ('atriacalendar', '0010_atriaoccurrence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atriaorganization',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atriaorganization',
            name='org_name',
        ),
        migrations.RemoveField(
            model_name='atriaorganization',
            name='org_name_en',
        ),
        migrations.RemoveField(
            model_name='atriaorganization',
            name='org_name_es',
        ),
        migrations.RemoveField(
            model_name='atriaorganization',
            name='org_name_fr',
        ),
        migrations.RemoveField(
            model_name='atriaorganization',
            name='org_name_zh_hans',
        ),
        migrations.RemoveField(
            model_name='atriarelationship',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atriarelationship',
            name='org',
        ),
        migrations.RemoveField(
            model_name='atriarelationship',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='atriaorganization',
            name='indyorganization_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indy_community.IndyOrganization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='atriarelationship',
            name='indyorgrelationship_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indy_community.IndyOrgRelationship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='indyuser_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='indy_community.IndyUser'),
            preserve_default=False,
        ),
    ]
