# Generated by Django 2.0.10 on 2019-07-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0011_relationtype_is_org_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriaoccurrence',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
