# Generated by Django 2.1.7 on 2019-05-26 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0009_auto_20190430_0331'),
        ('atriacalendar', '0011_relationtype_is_org_relation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certification_data', models.TextField(blank=True, max_length=4000, null=True)),
                ('verified', models.BooleanField(default=True)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndySchema')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atriacalendar.AtriaRelationship')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.AgentConversation')),
            ],
        ),
    ]
