# Generated by Django 2.1.7 on 2019-05-27 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indy_community', '0011_merge_20190501_0116'),
        ('atriacalendar', '0012_membercertification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeighbourCertification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.BooleanField(default=True)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.IndySchema')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indy_community.AgentConversation')),
            ],
        ),
    ]
