# Generated by Django 2.1.7 on 2019-08-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0013_auto_20190822_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atriavolunteeropportunity',
            name='title',
            field=models.TextField(blank=True, max_length=80),
        ),
    ]
