# Generated by Django 2.0.10 on 2019-09-06 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0014_auto_20190825_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriaoccurrence',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
