# Generated by Django 2.2.4 on 2019-09-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0014_auto_20190825_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='atriaorganization',
            name='tagline',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
