# Generated by Django 2.1.7 on 2019-09-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atriacalendar', '0015_atriaorganization_tagline'),
        ('atriacalendar', '0016_user_phone_number'),
    ]

    operations = [
    ]
